name: 'JCommandEssentials'
version: 2.9
authors: [Jamesst20]
main: com.jamesst20.jcommandessentials.JCMDEssentials.JCMDEss
commands:
   JCommandEssentials:
       description: 'JCommandsEssentials plugin'
       usage: /jcommandessentials
       aliases: [jcmdess]
   EnableCmd:
       description: 'Enable a JCMDEssentials Command'
       usage: /enablecmd <cmd>
   DisableCmd:
       description: 'Disable a JCMDEssentials Command'
       usage: /disablecmd <cmd>
   SetHome:
       description: 'Set your home location'
       usage: /setHome [Optional Home Name]
   Home:
       description: 'Teleport to your home location'
       usage: /Home [Optional Home Name]
       aliases: tphome
   Weather:
       description: 'Set the weather of the current or other worlds'
       usage: /weather <sun,rain,storm,thunder> [world]
       aliases: [sun, rain, storm, thunder]
   Tpa:
       description: 'Ask a player to teleport to him'
       usage: /tpa <player>
   TpAccept:
       description: 'Accept a teleport request'
       usage: /tpaccept
       aliases: tpaaccept
   TpDeny:
       description: 'Deny a teleport request'
       usage: /tpdeny
       aliases: tpadeny
   Tp:
       description: 'Teleport yourself or another player to a player'
       usage: /tp <player> [player]
   TpAll:
       description: 'Teleport all players to you'
       usage: /tpall
   TpHere:
       description: 'Teleport a player to your location'
       usage: /tphere <player>
   Time:
       description: 'Set the time of a world'
       usage: /day [world], /night [world], /time day/night [world]
       aliases: [day, night]
   Broadcast:
       description: 'Broadcast a message'
       usage: /broadcast <message>
   Spawn:
       description: 'Teleport yourself or another player to spawn'
       usage: /spawn [player]
   SetSpawn:
       description: 'Set default server spawn'
       usage: /setspawn
   Fly:
       description: 'Enabled or disable fly for yourself or another player'
       usage: /fly [player]
   God:
       description: 'Enable or disable god mode for yourself or another player'
       usage: /god [player]
       aliases: ungod
   Motd:
       description: 'Read the message of the day'
       usage: /motd
   Freeze:
       description: 'Prevent a player from moving'
       usage: /freeze <player>
       aliases: unfreeze
   Lock:
       description: 'Lock the server/player : Prevent breaking/placing blocks, chat messages and mobs spawning'
       usage: /lock [player]
       aliases: unlock
   ServerMotd:
       description: 'Set the server list motd'
       usage: /servermotd set <motd>, /servermotd enable, /servermotd disable
   Sudo:
       description: 'Run a command as another player'
       usage: /sudo <player> <command [args]>
   GameMode:
       description: 'Change your or a player gamemode'
       usage: /<gamemode/gm> <creative/survival/adventure> [player] or /<creative/survival/adventure> [player]
       aliases: [gm, survival, creative, adventure]
   Heal:
       description: 'Heal a player (Health and Food)'
       usage: /heal
   Msg:
       description: 'Send a private message to a player'
       usage: /msg <player> <message> or /pm <player> <message>
       aliases: [pm, tell]
   Staff:
       description: 'Send a message to the staff chat'
       usage: /staff <message>
   Tpc:
       description: 'Teleport yourself or a player to coordinates'
       usage: /tpc <x> <y> <z> [player]
       aliases: [tppos, tpos, tpcoord]
   Kick:
       description: 'Kick a player'
       usage: /kick <player> [reason]
   Ban:
       description: 'Ban a player'
       usage: /ban <player> [reason]
   Unban:
       description: 'Unban a player'
       usage: /unban <player>
   ClearInventory:
       description: 'Clear your or a player inventory'
       usage: /clearinventory [player]
       aliases: [ci, clear, clearinv, /ciinv]
   Kill:
       description: 'Kill yourself or a player'
       usage: /kill [player/all/*]
   Workbench:
       description: 'Force opening a workbench anywhere'
       usage: /workbench
       aliases: [craft, crafting, craftingtable, crafttable, wb, ct]
   FlySpeed:
       description: 'Get or set fly speed'
       usage: /flyspeed get [player] or /flyspeed set <speed> [player]
   OpenInventory:
       description: 'Open the inventory of a player'
       usage: /openinventory <player>
       aliases: [openinv, invopen, inventoryopen, oi]
   Vanish:
       description: 'Make yourself or a player invisible/visible from other players'
       usage: /vanish [player]
       aliases: unvanish
   Afk:
       description: 'Tells everyone that you are now back or away'
       usage: /afk or /afk [enable/disable/delay] [delay]
       aliases: unafk
   KillMobs:
       description: 'Kill mobs on the server'
       usage: /killmobs [animals/monsters/MobName]
       aliases: [killmob, killallmob, killallmobs]
   SpawnMob:
        description: 'Spawn mobs'
        usage: /spawnmob <mob> <quantity>
        aliases : spawnmobs
   Handicap:
        description: 'Block a player from using commands'
        usage: /handicap <player>
        aliases: unhandicap
   Ip:
        description: 'Get your or a player IP'
        usage: /ip [player]
        aliases: [getip, ipaddress, getipaddress]
   Mute:
        description: 'Mute a player'
        usage: /mute <player>
        aliases: unmute
   TpThere:
        description: 'Teleport yourself or a player to your target block'
        usage: /tpthere [player]
        aliases: put
   SetExp:
        description: 'Set your or a player experience level'
        usage: /setexp [player] <exp>
        aliases: [setxp, xp, exp]
   Enchant:
        description: 'Enchant the item you are holding'
        usage: /enchant <enchantment> <level>
        aliases: [enchantment, enchantments, enchantitem]
   WalkSpeed:
        description: 'Manage your or a player walking speed'
        usage: /walkspeed get [player], /walkspeed set <speed> [player]
        aliases: [wspeed, speedwalk, walk, run]
   TpBack:
        description: 'Teleport to your last location'
        usage: /tpback [player]
        aliases: [teleportback, tplastlocation, back, teleportlastlocation, tplast, teleportlast]
   Whois:
        description: 'Get info of a player'
        usage: /whois <player>
        aliases: [playerinfo, getplayerinfo, getpinfo, pinfo, playerinfo]
   Warp:
        description: 'Teleport or edit a warp'
        usage: /warp <name>, /warp <add/delete> <name>
   WhatIsIt:
        description: 'Give informations about an item'
        usage: /whatisit
        aliases: [wit, whatisthis, wti, wii]
   TpaHere:
        description: 'Ask to teleport to you a player'
        usage: /tpahere <player>
        aliases: [tpherea, atphere]
   WaterWalk:
        description: 'Allow yourself or a player to walk on water'
        usage: /waterwalk [player]
        aliases: [wwalk]
   Armor:
        description: 'Give to yourself or a player an armor'
        usage: /armor [player] <material>
        aliases: [armour]
   Shoot:
        description: 'Shoot yourself or a player into the air'
        usage: /shoot [player]
        aliases: [throw]
   SetItemName:
        description: 'Set the name of the item you are holding'
        usage: /setitemname <name>
        aliases: [iname, itemname]
   SetItemDescription:
        description: 'Set the description of the item you are holding'
        usage: /setitemdescription <line 1> [line 2] [line 3]
        aliases: [idescription, idesc, itemdescription, itemdesc]
   FreeMe:
        description: 'Throw and set on fire enemies around you'
        usage: /freeme [Player]
        aliases: [sparta, freedom]
   Flat:
       description: 'Make the map flat for a specific radius'
       usage: /flat <radius>
       aliases: [makeflat]
   Strike:
       description: 'Strike lightning a player'
       usage: /strike <player>
       aliases: [thunder, zeus]
   Spy:
       description: 'Spy a player private messages'
       usage: /spy <player or clear>